# -*- coding: utf-8 -*-
"""codingan MIT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vNt7oBUAkcDoJhwHBvx-PuKOqNhF950Y
"""

!pip install flask flask-cors pyngrok

from pyngrok import ngrok
ngrok.set_auth_token("3CLgjpTkYCWTF8LrWzxiq0NxGuQ_rwvVPXHGpZfTpzd9J1Da")

from flask import Flask, jsonify, request
from flask_cors import CORS
from pyngrok import ngrok

app = Flask(__name__)
CORS(app)

# 1. SETTING NGROK (Ganti Token ini jika punya sendiri)
# ngrok.set_auth_token("MASUKKAN_TOKEN_NGROK_MU")

# 2. DATABASE DUMMY (Sesuai permintaanmu)
users = {
    "naufal": {
        "password": "123",
        "nama": "Pemilik Rekening:Izzan itsar",
        "saldo": "0",
        "status": "Status:Aktif"
    },
    "ziyad": {
        "password": "456",
        "nama": "Pemilik Rekening: Ziyad Nopal",
        "saldo": "0",
        "status": "Status: Aktif"
    }
}

@app.route("/login", methods=["POST"])
def login():
    data = request.json
    username = data.get("username")
    password = data.get("password")

    print(f"Mencoba login: {username}") # Biar kelihatan di log Colab

    if username in users and users[username]["password"] == password:
        # Kirim data lengkap ke App Inventor
        return jsonify({
            "status_login": "success",
            "nama": users[username]["nama"],
            "saldo": users[username]["saldo"],
            "status": users[username]["status"]
        })
    else:
        return jsonify({"status_login": "failed", "message": "Login Gagal"}), 401

try:
    # Buka terowongan ngrok di port 5000
    public_url = ngrok.connect(5000)
    print("--- SERVER BERHASIL JALAN ---")
    print("URL BARU KAMU:", public_url)
    print("MASUKKAN DI APP INVENTOR:", str(public_url).replace('\"','') + "/login")
    print("-----------------------------")

    app.run(port=5000)
except Exception as e:
    print("Error:", e)



